cpdb_results = cpdb_statistical_analysis_method.call(cpdb_file_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CPS_OV1RtOV3/cellphonedb/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CPS_OV1RtOV3/cellphonedb/CellphoneDB_meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CPS_OV1RtOV3/cellphonedb/CellphoneDB_count.txt',counts_data = 'hgnc_symbol',output_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CPS_OV1RtOV3/cellphonedb/output2/')

cpdb_results = cpdb_statistical_analysis_method.call(cpdb_file_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/All.meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/All.count.txt',counts_data = 'hgnc_symbol',output_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/output1/')

cpdb_results = cpdb_statistical_analysis_method.call(cpdb_file_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Recur_meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Recur_count.txt',counts_data = 'hgnc_symbol',output_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/output_recur/')

cpdb_results = cpdb_statistical_analysis_method.call(cpdb_file_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_count.txt',counts_data = 'hgnc_symbol',output_path = '/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/output_non/')

cpdb_results = cpdb_degs_analysis_method.call(cpdb_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_count.txt',degs_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_markers_new.txt',counts_data='hgnc_symbol',output_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/output_non_DEG/')

cpdb_results = cpdb_degs_analysis_method.call(cpdb_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Recur_meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Recur_count.txt',degs_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Recur_markers_new.txt',counts_data='hgnc_symbol',output_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/output_Recur_DEG/')

cpdb_results = cpdb_degs_analysis_method.call(cpdb_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/cellphonedb.zip',meta_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_meta.txt',counts_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_count.txt',degs_file_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/Non_markers_new.txt',counts_data='hgnc_symbol',output_path='/home/jhy/spatial_transcriptomics/220905/result/seurat/CellPhoneDB/output_non_DEG_0.1/',threshold = 0.1)

